- name: 'Download do wordpress'
  get_url:
    url: https://wordpress.org/wordpress-3.9.40.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: 'Descompactar o arquivo tar.gz do wordpress'
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes
  become: yes

- name: 'Copia os arquivos do wordpress do gest para o host'
  copy:
    src: "{{wp_installation_dir }}/wp-config-sample.php" 
    dest: "{{wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Configura o arquivo wp-confih.php de acordo com o datasource'
  replace:
    path: "{{wp_installation_dir }}/wp-config.php"
    regexp: '{{ item.regex}}'
    replace: '{{ item.value}}'
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}"}
    - { regex: 'username_here', value: "{{ wp_user_name }}"}
    - { regex: 'password_here',value: "{{ wp_user_password }}"}
    - { regex: 'localhost',value: "{{ wp_db_ip }}"}
  become: yes

- name: 'Copia o arquivos 000-default.conf do host para o gest'
  template: 
    src: templates/000-default.conf.j2
    dest: /etc/apache2/sites-available
  become: yes
  notify:
    - restart apache2