---
- hosts: all
  tasks:
    - name: 'Instala o php mais recente'
      apt:
        name: php
        state: latest
      become: yes
    - name: 'Instala o apache2'
      apt:
        name: apache2
        state: latest
      become: yes
    - name: 'Instala o modphp'
      apt:
        name: libapache2-mod-php
        state: latest
      become: yes