# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end
  
  config.vm.define "phpweb" do |phpweb|
    phpweb.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "ubuntu_focal_php"
    end    
    phpweb.vm.network "public_network", ip: "192.168.1.18", bridge: "enp0s31f6"

    phpweb.vm.provision "shell",
      inline: "cat /configs/id_focal64.pub >> .ssh/authorized_keys"
  end
  
    config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.1.19", bridge: "enp0s31f6"
    
    ansible.vm.provision "shell",
      inline: "apt-get update && \
               apt-get install -y software-properties-common && \
               apt-add-repository --yes --update ppa:ansible/ansible && \
               apt-get install -y ansible"

    ansible.vm.provision "shell",
      inline: "cp /vagrant/id_focal64 /home/vagrant/.ssh/ \
      && chmod 600 /home/vagrant/.ssh/id_focal64 \
      && chown vagrant:vagrant /home/vagrant/.ssh/id_focal64"            
  end
end
