# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end
  
  config.vm.define "wordpress" do |wordpress|
    wordpress.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end    
    wordpress.vm.network "public_network", ip: "192.168.1.18", bridge: "enp0s31f6"

    wordpress.vm.provision "shell",
      inline: "cat /vagrant/configs/id_focal64.pub >> .ssh/authorized_keys"
  end
  
  config.vm.define "mysql" do |mysql|
    mysql.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end    
    mysql.vm.network "public_network", ip: "192.168.1.20", bridge: "enp0s31f6"

    mysql.vm.provision "shell",
      inline: "cat /vagrant/configs/id_focal64.pub >> .ssh/authorized_keys"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.1.19", bridge: "enp0s31f6"
    
    ansible.vm.provision "shell",
      inline: "apt-get update && \
              apt-get install -y software-properties-common && \
              apt-add-repository --yes ppa:ansible/ansible && \
              apt-get update && \
              apt-get install -y ansible"

    # ansible.vm.provision "shell",
    #   inline: "apt-get update && \
    #           apt-get install -y software-properties-common && \
    #           add-apt-repository --yes ppa:fkrull/deadsnakes && \
    #           apt-get update && \
    #           apt-get install -y python3.5"

    ansible.vm.provision "shell",
      inline: "cp /vagrant/id_focal64 /home/vagrant/.ssh/ \
      && chmod 600 /home/vagrant/.ssh/id_focal64 \
      && chown vagrant:vagrant /home/vagrant/.ssh/id_focal64"            
      
    ansible.vm.provision "shell",
        inline: "ansible-playbook -i /vagrant/hosts /vagrant/playbook.yml"
  end
end
